import { v4 as uuidv4 } from 'uuid'

export const items = [
    {
        id: uuidv4(),
        nombre: "Ryzen 5 4600G",
        precio: "768",
        img: "ryzen-5-4600G",
        categoria: "hardware", 
    },
    {
        id: uuidv4(),
        nombre: "Ryzen 5 5600G",
        precio: "840",
        img: "ryzen-5-5600G",
        categoria: "hardware", 
    },
    {
        id: uuidv4(),
        nombre: "Placa asus prime a320m-k",
        precio: "253.13",
        img: "placa-asus-prime-a320m",
        categoria: "hardware", 
    },
    {
        id: uuidv4(),
        nombre: "Memoria ram teamgroup ddr3 8gb 1600mhz",
        precio: "150",
        img: "memoria-ram-teamgroup-ddr3-8gb-1600mhz",
        categoria: "hardware", 
    },
    {
        id: uuidv4(),
        nombre: "Disco duro solido wester digital blue 250gb",
        precio: "170",
        img: "disco-solido-wester-digital-blue-250gb",
        categoria: "hardware", 
    },
    {
        id: uuidv4(),
        nombre: "Tarjeta de video Geforce GTX 1660 Super",
        precio: "1,229",
        img: "tarjeta-de-video-geforce-gtx-1660-super",
        categoria: "hardware", 
    },
    {
        id: uuidv4(),
        nombre: "Tarjeta de video RX 550 4gb gddr5",
        precio: "690",
        img: "tarjeta-de-video-rx-550",
        categoria: "hardware", 
    },
    {
        id: uuidv4(),
        nombre: "Case avatec gamer cca-3243b 450w rgb",
        precio: "202.50",
        img: "case-avatec-gamer-cca-3243b-450w-rgb",
        categoria: "hardware", 
    },
    {
        id: uuidv4(),
        nombre: "Placa asus prime b365m-a lga1151",
        precio: "324",
        img: "placa-asus-prime-b365m-a-lga1151",
        categoria: "hardware", 
    },
    {
        id: uuidv4(),
        nombre: "Fuente de poder gigabyte gp-p750gm 80 plus gold 750w",
        precio: "388.80",
        img: "fuente-de-poder-gigabyte-gp-p750gm-80-plus-gold-750w",
        categoria: "hardware", 
    },
    {
        id: uuidv4(),
        nombre: "Adaptador ugreen usb a sata para disco duro de laptop",
        precio: "47",
        img: "adaptador-ugreen-usb-a-sata-para-disco-duro-de-laptop",
        categoria: "perifericos", 
    },
    {
        id: uuidv4(),
        nombre: "Antivirus escan (edicioncyber vacuna)",
        precio: "42",
        img: "antivirus-escan-(edicioncyber-vacuna)",
        categoria: "software", 
    },
    {
        id: uuidv4(),
        nombre: "Audifono disney frozen gt-9300",
        precio: "35.44",
        img: "audifono-disney-frozen-gt-9300",
        categoria: "perifericos", 
    },
    {
        id: uuidv4(),
        nombre: "Audifono deportivo teros te-8090 recargable",
        precio: "35.44",
        img: "audifono-deportivo-teros-te-8090-recargable",
        categoria: "perifericos", 
    },
    {
        id: uuidv4(),
        nombre: "Audifono halion gaming s1 scorpion",
        precio: "40",
        img: "audifono-halion-gaming-s1-scorpion",
        categoria: "perifericos", 
    },
    {
        id: uuidv4(),
        nombre: "Pad mouse gamer rgb 80x30",
        precio: "40.55",
        img: "pad-mouse-gamer-rgb-80x30",
        categoria: "perifericos", 
    },
    {
        id: uuidv4(),
        nombre: "Mouse logitech g203 gamer 8000dpi rgb black",
        precio: "146.81",
        img: "mouse-logitech-g203-gamer-8000dpi-rgb-black",
        categoria: "perifericos", 
    },
    {
        id: uuidv4(),
        nombre: "Kit halion kraken ha-506c teclado y mouse",
        precio: "68.85",
        img: "kit-halion-kraken-ha-506c-teclado-y-mouse",
        categoria: "perifericos", 
    },
    {
        id: uuidv4(),
        nombre: "Kit enkore brain 3 ent g1005-3 teclado mouse pad mouse rgb",
        precio: "72.90",
        img: "kit-enkore-brain-3-ent-g1005-3-teclado-mouse-pad-mouse-rgb",
        categoria: "perifericos", 
    },
    {
        id: uuidv4(),
        nombre: "Kit enkore brain 4 teclado mouse y pad mouse rgb ent g1005-4",
        precio: "72.90",
        img: "kit-enkore-brain-4-teclado-mouse-y-pad-mouse-rgb-ent-g1005-4",
        categoria: "perifericos", 
    },
    {
        id: uuidv4(),
        nombre: "KASPERSKY TOTAL SECURITY 2015 3PC PROMOCIÓN",
        precio: "276.25",
        img: "KASPERSKY-TOTAL-SECURITY-2015-3PC-PROMOCIÓN",
        categoria: "software", 
    },
    {
        id: uuidv4(),
        nombre: "MICROSOFT WINDOWS SERVER 2012 R2 ESSENTIALS X64",
        precio: "1625",
        img: "MICROSOFT-WINDOWS-SERVER-2012-R2-ESSENTIALS-X64",
        categoria: "software", 
    },
    {
        id: uuidv4(),
        nombre: "MICROSOFT WINDOWS SERVER STANDARD 2012 X64",
        precio: "2925",
        img: "MICROSOFT-WINDOWS-SERVER-STANDARD-2012-X64",
        categoria: "software", 
    },
    {
        id: uuidv4(),
        nombre: "SOFTWARE ESET SMART SECURITY EDICION 2016 2 PCS+1 ANDROID",
        precio: "72.90",
        img: "SOFTWARE-ESET-SMART-SECURITY-EDICION-2016-2-PCS+1-ANDROID",
        categoria: "software", 
    }
]